[package]
name = "sovereign-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "testapp"
path = "src/bin/main.rs" #

[dependencies]
sovereign-sdk =  { path = "../sovereign-sdk" }
tendermint = "0.27"

prost = "0.11"
prost-types = "0.11"

# Convenience
reqwest = "0.11.13"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1" 
hex = { version = "0.4.3", features = ["serde"] }
hex-literal = "0.3.4"
base64 = "0.13.1"

[build-dependencies]
prost-build = { version = "0.11" }
